all:
	cd vga && $(MAKE) all && $(MAKE) link
	cd pit && $(MAKE) all && $(MAKE) link
	cd keyb && $(MAKE) all && $(MAKE) link

debug:
	cd vga && $(MAKE) debug && $(MAKE) link
	cd pit && $(MAKE) debug && $(MAKE) link
	cd keyb && $(MAKE) debug && $(MAKE) link
