all:
	cd memory && $(MAKE) all && $(MAKE) link
	cd strings && $(MAKE) all && $(MAKE) link
	#cd os_specific && $(MAKE) all && $(MAKE) link

debug:
	cd memory && $(MAKE) debug && $(MAKE) link
	cd strings && $(MAKE) debug && $(MAKE) link
	#cd os_specific && $(MAKE) debug && $(MAKE) link
